import {
  Organization,
  User,
  Employee,
  Department,
  Designation,
  Holiday,
  LeaveBalance,
  LeaveRequest,
  AttendanceRecord,
  SalaryStructure,
  PayrollRun,
  PayrollItem,
  Payslip,
  Announcement,
  NotificationItem,
  AuditLog,
  EmployeeRequest,
} from "@/types";
import { DEFAULT_STATUTORY_CONFIG } from "@/lib/payroll/engine";

export const DEMO_ORGANIZATION: Organization = {
  id: "org-coralgenz-01",
  name: "Coralgenz Technologies Pvt. Ltd.",
  tagline: "Smart Payroll & Workforce Management",
  logoUrl: "/logo.png",
  email: "admin@coralgenz.co.in",
  phone: "+91 422 456 7890",
  website: "https://coralgenz.co.in",
  address: "Tristar Tower, 2nd Floor, Avinashi Road, Peelamedu",
  city: "Coimbatore",
  state: "Tamil Nadu",
  country: "India",
  postalCode: "641004",
  currency: "INR",
  currencySymbol: "₹",
  financialYearStartMonth: 4,
  payrollFrequency: "monthly",
  timeZone: "Asia/Kolkata",
  workingDays: [1, 2, 3, 4, 5],
  weeklyOffDays: [0, 6],
  employeeIdPrefix: "CGG-EMP-",
  payslipNumberPrefix: "CGG-PS-",
  panNumber: "AAACC1234K",
  gstin: "33AAACC1234K1Z5",
  pfRegistrationNumber: "TN/CBE/0012345/000",
  esiRegistrationNumber: "51000123450000001",
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2026-08-01T00:00:00.000Z",
  onboardingCompleted: true,
};

export const DEMO_USERS: User[] = [
  {
    id: "usr-superadmin-01",
    email: "karthick@coralgenz.co.in",
    displayName: "Karthick Krishna",
    role: "super_admin",
    organizationId: "org-coralgenz-01",
    employeeId: "CGG-EMP-0001",
    photoURL: "/logo.png",
    phone: "+91 98422 43210",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-26T00:00:00.000Z",
    isActive: true,
  },
];

export const DEMO_EMPLOYEES: Employee[] = [];

export const DEMO_DEPARTMENTS: Department[] = [
  {
    id: "dept-01",
    organizationId: "org-coralgenz-01",
    name: "Engineering",
    code: "ENG",
    description: "Full stack web, mobile, cloud infrastructure, and DevOps",
    colorHex: "#0284c7",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-02",
    organizationId: "org-coralgenz-01",
    name: "Product Design",
    code: "DES",
    description: "UI/UX design systems, micro-interactions, and motion graphics",
    colorHex: "#ec4899",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-03",
    organizationId: "org-coralgenz-01",
    name: "Human Resources",
    code: "HR",
    description: "Talent acquisition, employee welfare, and company culture",
    colorHex: "#10b981",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-04",
    organizationId: "org-coralgenz-01",
    name: "Finance & Accounts",
    code: "FIN",
    description: "Statutory payroll, tax audits (TDS/PF/ESI), and budgeting",
    colorHex: "#8b5cf6",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-05",
    organizationId: "org-coralgenz-01",
    name: "Growth & Marketing",
    code: "MKT",
    description: "Digital brand marketing, SEO, social media, and community",
    colorHex: "#f59e0b",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-06",
    organizationId: "org-coralgenz-01",
    name: "Client Operations",
    code: "OPS",
    description: "Client success, onboarding support, and business operations",
    colorHex: "#06b6d4",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
  {
    id: "dept-07",
    organizationId: "org-coralgenz-01",
    name: "AI & Innovation",
    code: "AI",
    description: "Large Language Models, agentic workflows, and RAG pipelines",
    colorHex: "#6366f1",
    employeeCount: 0,
    monthlyPayrollCost: 0,
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
    isArchived: false,
  },
];

export const DEMO_DESIGNATIONS: Designation[] = [
  {
    id: "desig-01",
    organizationId: "org-coralgenz-01",
    title: "Lead Full Stack Architect",
    departmentId: "dept-01",
    departmentName: "Engineering",
    description: "Technical leadership, Next.js architecture, and cloud systems",
    minSalary: 100000,
    maxSalary: 200000,
    employeeCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "desig-02",
    organizationId: "org-coralgenz-01",
    title: "Senior Software Engineer",
    departmentId: "dept-01",
    departmentName: "Engineering",
    description: "Full-stack web application development",
    minSalary: 70000,
    maxSalary: 120000,
    employeeCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "desig-03",
    organizationId: "org-coralgenz-01",
    title: "UI/UX Product Designer",
    departmentId: "dept-02",
    departmentName: "Product Design",
    description: "Product design systems and user experience",
    minSalary: 50000,
    maxSalary: 95000,
    employeeCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "desig-04",
    organizationId: "org-coralgenz-01",
    title: "HR Operations Lead",
    departmentId: "dept-03",
    departmentName: "Human Resources",
    description: "Employee lifecycle and onboarding",
    minSalary: 55000,
    maxSalary: 90000,
    employeeCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "desig-05",
    organizationId: "org-coralgenz-01",
    title: "Payroll & Finance Manager",
    departmentId: "dept-04",
    departmentName: "Finance & Accounts",
    description: "Payroll disbursements and tax compliance",
    minSalary: 65000,
    maxSalary: 110000,
    employeeCount: 0,
    status: "active",
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
];

export const DEMO_HOLIDAYS: Holiday[] = [
  {
    id: "hol-01",
    organizationId: "org-coralgenz-01",
    name: "New Year's Day",
    date: "2026-01-01",
    dayOfWeek: "Thursday",
    type: "public",
    description: "International New Year celebration",
    isRecurringYearly: true,
  },
  {
    id: "hol-02",
    organizationId: "org-coralgenz-01",
    name: "Pongal / Makara Sankranti",
    date: "2026-01-14",
    dayOfWeek: "Wednesday",
    type: "public",
    description: "Tamil harvest festival celebration",
    isRecurringYearly: true,
  },
  {
    id: "hol-03",
    organizationId: "org-coralgenz-01",
    name: "Thiruvalluvar Day",
    date: "2026-01-15",
    dayOfWeek: "Thursday",
    type: "public",
    description: "Honoring great Tamil philosopher Thiruvalluvar",
    isRecurringYearly: true,
  },
  {
    id: "hol-04",
    organizationId: "org-coralgenz-01",
    name: "Republic Day",
    date: "2026-01-26",
    dayOfWeek: "Monday",
    type: "public",
    description: "Indian Constitution Day",
    isRecurringYearly: true,
  },
  {
    id: "hol-05",
    organizationId: "org-coralgenz-01",
    name: "Tamil New Year / Puthandu",
    date: "2026-04-14",
    dayOfWeek: "Tuesday",
    type: "public",
    description: "Tamil solar calendar New Year",
    isRecurringYearly: true,
  },
  {
    id: "hol-06",
    organizationId: "org-coralgenz-01",
    name: "May Day / Labor Day",
    date: "2026-05-01",
    dayOfWeek: "Friday",
    type: "public",
    description: "International Workers' Day",
    isRecurringYearly: true,
  },
  {
    id: "hol-07",
    organizationId: "org-coralgenz-01",
    name: "Independence Day",
    date: "2026-08-15",
    dayOfWeek: "Saturday",
    type: "public",
    description: "Indian Independence Day",
    isRecurringYearly: true,
  },
  {
    id: "hol-08",
    organizationId: "org-coralgenz-01",
    name: "Vinayakar Chaturthi",
    date: "2026-09-14",
    dayOfWeek: "Monday",
    type: "public",
    description: "Lord Ganesha festival",
    isRecurringYearly: true,
  },
  {
    id: "hol-09",
    organizationId: "org-coralgenz-01",
    name: "Gandhi Jayanti",
    date: "2026-10-02",
    dayOfWeek: "Friday",
    type: "public",
    description: "Mahatma Gandhi birthday",
    isRecurringYearly: true,
  },
  {
    id: "hol-10",
    organizationId: "org-coralgenz-01",
    name: "Deepavali",
    date: "2026-11-08",
    dayOfWeek: "Sunday",
    type: "public",
    description: "Festival of Lights",
    isRecurringYearly: true,
  },
  {
    id: "hol-11",
    organizationId: "org-coralgenz-01",
    name: "Christmas Day",
    date: "2026-12-25",
    dayOfWeek: "Friday",
    type: "public",
    description: "Christmas celebrations",
    isRecurringYearly: true,
  },
];

export const DEMO_SALARY_STRUCTURE: SalaryStructure = {
  id: "struct-01",
  organizationId: "org-coralgenz-01",
  name: "Standard Indian Statutory Structure",
  description: "Standard CTC distribution complying with EPF, ESI, Gratuity, Professional Tax, and Income Tax TDS.",
  isDefault: true,
  basicSalaryPercent: 45,
  hraPercent: 50,
  conveyanceAllowance: 1600,
  medicalAllowance: 1250,
  specialAllowancePercent: 20,
  statutoryConfig: DEFAULT_STATUTORY_CONFIG,
  customEarnings: [],
  customDeductions: [],
  createdAt: "2024-01-01T00:00:00.000Z",
  updatedAt: "2026-08-01T00:00:00.000Z",
};

export const DEMO_LEAVE_BALANCES: LeaveBalance[] = [];
export const DEMO_LEAVE_REQUESTS: LeaveRequest[] = [];
export const DEMO_ATTENDANCE: AttendanceRecord[] = [];
export const DEMO_PAYROLL_RUNS: PayrollRun[] = [];
export const DEMO_PAYROLL_ITEMS: PayrollItem[] = [];
export const DEMO_PAYSLIPS: Payslip[] = [];
export const DEMO_ANNOUNCEMENTS: Announcement[] = [];
export const DEMO_NOTIFICATIONS: NotificationItem[] = [];
export const DEMO_AUDIT_LOGS: AuditLog[] = [];
export const DEMO_REQUESTS: EmployeeRequest[] = [];
